<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-M9LRRON" ignored="0" name="GeneratingCredentialsForJenkins" tests="8" failures="1" timestamp="03 сен 2019 07:54:08 GMT" time="15.599" errors="0">
  <testcase name="registration" time="11.946" classname="com.AppConfiguring"/>
  <testcase name="checkThatAccountExists" time="3.598" classname="com.AppConfiguring"/>
  <testcase name="confirmRegistration" time="0.003" classname="com.AppConfiguring">
    <failure type="java.lang.AssertionError" message="ACCOUNT ALREADY EXIST">
      <![CDATA[java.lang.AssertionError: ACCOUNT ALREADY EXIST
at com.AppConfiguring.confirmRegistration(AppConfiguring.java:65)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 47 stack frames]]>
    </failure>
  </testcase> <!-- confirmRegistration -->
  <testcase name="createApp" time="0.0" classname="com.AppConfiguring">
    <skipped/>
  </testcase> <!-- createApp -->
  <testcase name="uploadCertificates" time="0.0" classname="com.AppConfiguring">
    <skipped/>
  </testcase> <!-- uploadCertificates -->
  <testcase name="setAdditionalOptions" time="0.0" classname="com.AppConfiguring">
    <skipped/>
  </testcase> <!-- setAdditionalOptions -->
  <testcase name="getCredentials" time="0.0" classname="com.AppConfiguring">
    <skipped/>
  </testcase> <!-- getCredentials -->
  <testcase name="createJenkinsCreds" time="0.0" classname="com.AppConfiguring">
    <skipped/>
  </testcase> <!-- createJenkinsCreds -->
</testsuite> <!-- GeneratingCredentialsForJenkins -->
